# Copyright 2026 Google. This software is provided as-is, without warranty or representation for any use or purpose. Your use of it is subject to your agreement with Google.
"""
Output Schemas for QAI Optimization Framework.

This module defines the Pydantic models used for structuring the output data,
including analysis results and evaluation metrics.
"""

from typing import Optional
from pydantic import BaseModel, Field


class AnalysisEntry(BaseModel):
    """
    Represents a single entry of analysis results for a resource.

    Attributes:
        resource_name (str): The full resource name (e.g., conversation name).
        question_id (str): The ID of the evaluation question.
        question_body (str): The text of the evaluation question.
        analysis_text (Optional[str]): The text generated during analysis (e.g. answer rationale).
        score (Optional[str]): The score or label assigned (e.g., "Pass", "Fail").
        generated_at (str): Timestamp of when the analysis was generated.
    """

    resource_name: str = Field(..., description="The full resource name.")
    question_id: str = Field(..., description="The ID of the evaluation question.")
    question_body: str = Field(..., description="The text of the evaluation question.")
    analysis_text: Optional[str] = Field(
        None, description="The text generated during analysis (e.g. answer rationale)."
    )
    score: Optional[str] = Field(None, description="The score or label assigned.")
    generated_at: str = Field(
        ..., description="Timestamp of when the analysis was generated."
    )


class EvaluationResult(BaseModel):
    """
    Represents the result of comparing a single LLM output against a golden reference.

    Attributes:
        resource_id (str): The ID of the resource (e.g., conversation ID).
        question_id (str): The ID of the evaluation question.
        predicted_answer (str): The answer generated by the LLM.
        golden_answer (str): The ground truth answer from the golden set.
        is_correct (bool): Whether the prediction matches the golden answer.
        rationale (Optional[str]): Explanation for the evaluation result (e.g., why it failed).
    """

    resource_id: str = Field(..., description="The ID of the resource.")
    question_id: str = Field(..., description="The ID of the evaluation question.")
    predicted_answer: str = Field(..., description="The answer generated by the LLM.")
    golden_answer: str = Field(
        ..., description="The ground truth answer from the golden set."
    )
    is_correct: bool = Field(
        ..., description="Whether the prediction matches the golden answer."
    )
    rationale: Optional[str] = Field(
        None, description="Explanation for the evaluation result (e.g., why it failed)."
    )


class EvaluationMetrics(BaseModel):
    """
    Aggregated evaluation metrics for a batch of results.

    Attributes:
        accuracy (float): Overall accuracy (correct predictions / total).
        precision (float): Weighted precision score.
        recall (float): Weighted recall score.
        f1_score (float): Weighted F1 score.
        total_samples (int): Total number of samples evaluated.
    """

    accuracy: float = Field(
        ..., description="Overall accuracy (correct predictions / total)."
    )
    precision: float = Field(..., description="Weighted precision score.")
    recall: float = Field(..., description="Weighted recall score.")
    f1_score: float = Field(..., description="Weighted F1 score.")
    cohens_kappa: float = Field(
        ..., description="Cohen's Kappa score for inter-rater agreement."
    )
    total_samples: int = Field(..., description="Total number of samples evaluated.")
